### PR TITLE
bump csv to 4.4

### PR DESCRIPTION
**Pull request by jcantrill**
Will need to bump min version to 4.3 once OLM had 4.3 content

cc @ewolinetz 

fixes: https://github.com/openshift/elasticsearch-operator/issues/208

### CODE REVIEW

**Comment by richm** [comment]
will also need to make a corresponding change to oal - hack/deploy-logging.sh

**Comment by ewolinetz** [comment]
is the diff accurate in that we no longer have 4.3 manifest files after this change?

**Comment by jcantrill** [comment]
> is the diff accurate in that we no longer have 4.3 manifest files after this change?
Yes.  for reasons I don't recall the decision was made to only have a single set of manifest files for any one version for the release

**Pull request merged**
