### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by josefkarasek**

### CODE REVIEW

**Comment by ewolinetz** [comment]
out of curiosity, did you run the e2e tests after updating the deps to ensure nothing breaks?

**Comment by richm** [comment]
@ewolinetz @jcantrill are we ready to merge this?

**Comment by ewolinetz** [comment]
@josefkarasek do you know if this is the most up to date dep update pr?

**Comment by josefkarasek** [comment]
> @josefkarasek do you know if this is the most up to date dep update pr?

It is not. I was hoping to land this together with upgrading the sdk. Let me update this update.

**Comment by josefkarasek** [comment]
Wait for openshift/elasticsearch-operator/pull/71 to merge first

**Comment by ewolinetz** [comment]
@josefkarasek #71 merged in

**Comment by richm** [comment]
there are definitely some problems with test-e2e.sh
```
hack/test-e2e.sh: line 23: sudo: command not found
...
# github.com/openshift/elasticsearch-operator/vendor/sigs.k8s.io/controller-runtime/pkg/client
vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go:49:24: undefined: v1.CreateOptions
vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go:67:24: undefined: v1.UpdateOptions
vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go:145:26: too many arguments in call to r.UpdateStatus
vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go:145:30: undefined: v1.UpdateOptions
FAIL	github.com/openshift/elasticsearch-operator/test/e2e [build failed]
```

**Comment by josefkarasek** [comment]
This patch introduced the breaking change, we have bad version of `k8s.io/apimachinery/pkg/apis/meta/v1`
```
--- a/vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
+++ b/vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
@@ -46,7 +46,7 @@ func (uc *unstructuredClient) Create(_ context.Context, obj runtime.Object) erro
        if err != nil {
                return err
        }
-       i, err := r.Create(u)
+       i, err := r.Create(u, metav1.CreateOptions{})
        if err != nil {
                return err
        }
@@ -64,7 +64,7 @@ func (uc *unstructuredClient) Update(_ context.Context, obj runtime.Object) erro
        if err != nil {
                return err
        }
-       i, err := r.Update(u)
+       i, err := r.Update(u, metav1.UpdateOptions{})
        if err != nil {
                return err
        }
@@ -142,7 +142,7 @@ func (uc *unstructuredClient) UpdateStatus(_ context.Context, obj runtime.Object
        if err != nil {
                return err
        }
-       i, err := r.UpdateStatus(u)
+       i, err := r.UpdateStatus(u, metav1.UpdateOptions{})
        if err != nil {
                return err
        }
```

**Comment by josefkarasek** [comment]
Closing due to inconsistency in our deps' deps. We will revisit this with the update of the sdk.

**Pull request closed without merging**
