### PR TITLE
Bug 1899905: Handle invalid json in delete script

### PR DESCRIPTION
**Pull request by huikang**
### Description
Handle invalid json input in the delete index script

/cc @ewolinetz 
/assign @jcantrill  

/cherry-pick 

### Links
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1899905

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/approve

**Comment by periklis** [comment]
/retitle Bug 1899905: Handle invalid json in delete script

**Review by periklis — APPROVED** [review]
/lgtm

**Pull request merged**
