### PR TITLE
[release-4.5] Bug 1899905: Handle invalid json in index delete script

### PR DESCRIPTION
**Pull request by huikang**
- Handle  exception in case es node is unavailable

### Description

Handle  exception in case es node is unavailable

/cc @ewolinetz 
/assign @periklis 

### Links
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1899905

### CODE REVIEW

**Comment by ewolinetz** [comment]
@huikang @periklis isn't this already being tracked in another cherrypick?

**Comment by periklis** [comment]
> @huikang @periklis isn't this already being tracked in another cherrypick?

Can you point us to the other cherry-pick please? I can't see anything.

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by ewolinetz** [comment]
closing as we'll get a cherrypick from https://github.com/openshift/elasticsearch-operator/pull/588
this PR also points to the 4.7 bz which is incorrect.

**Pull request closed without merging**
