### PR TITLE
Fixing skopeo auth issue in deploy-image.sh

### PR DESCRIPTION
**Pull request by nhosoi**
[ERROR]
+++ dirname hack/deploy-image.sh
+ skopeo copy --dest-tls-verify=false docker-daemon:quay.io/openshift/origin-cluster-logging-operator:latest docker://127.0.0.1:5000/openshift/origin-cluster-logging-operator:latest
time="..." level=fatal msg="Error trying to reuse blob sha256:... at destination: unable to retrieve auth token: invalid username/password"

### CODE REVIEW

**Comment by richm** [comment]
is this still a problem?  if not, can we close this PR?

**Comment by nhosoi** [comment]
> is this still a problem? if not, can we close this PR?

Without this PR, the CI tests are all working fine now.  I believe it was just a temporary issue and this PR is not needed any more.  I'm closing this PR.

**Pull request closed without merging**
