### PR TITLE
Adding safeguards to cronjob to be more resilient to es 500 responses

### PR DESCRIPTION
**Pull request by ewolinetz**
### Description
Note, do not link the bugzilla in the title. That is only relevant for the 4.6 branch cherrypick and will link it there.

During a load test it can happen where permissions are not correctly evaluated and a http 500 is returned when trying to get index aliases. It is observed to not be a constant issue and retry will usually be successful.

This PR adds retries into the cronjob curl commands for the case where this is an intermittent issue.

Due to how we store the responses with the retry we make them look like an array of json responses so that we can properly parse them out and evaluate what the last response was (because we either succeed eventually or we fail the whole time).

Also given delete and rollover were having issues with the same block of code I removed the delete pattern of building the python script inline and reused the one the rollover script was utilizing.

/cc @jcantrill @blockloop @periklis 

/cherry-pick release-5.0
/cherry-pick release-4.6

### Links
- Bugzilla: Addresses issue seen in https://bugzilla.redhat.com/show_bug.cgi?id=1928772

### CODE REVIEW

**Comment by ewolinetz** [comment]
/hold

want to add some more safeguarding based on an error i just saw (500 has been addressed)

**Review by periklis — COMMENTED** [review]
From a high level perspective it looks to me as it does what you describe it should do. I leave this w/o labels to the pythoneers to review in more detail.

**Review by blockloop — APPROVED** [review]
/lgtm

**Pull request merged**
