### PR TITLE
[release-4.6] Bug 1901299: Change ES Operator CSV to clarify the scope for this Operator

### PR DESCRIPTION
**Pull request by ewolinetz**
### Description
Manual cherrypick of https://github.com/openshift/elasticsearch-operator/pull/579

/cc @blockloop @periklis 

### Links
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1901299

### CODE REVIEW

**Review by periklis — APPROVED** [review]
/lgtm

**Review by blockloop — APPROVED** [review]
/lgtm

**Comment by ewolinetz** [comment]
/hold
need to add in missing line that was missed but required for the bz

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by periklis** [comment]
@markmc This looks like a trivial change, but for good reason mentioned here (https://bugzilla.redhat.com/show_bug.cgi?id=1901299#c1), we need to land this in 4.6.z

**Pull request merged**
