### PR TITLE
Bug 1892755: Update Elasticsearch dashboard

### PR DESCRIPTION
**Pull request by lukas-vlcek**
### Description

Updating Elasticsearch metrics dashboard. Improving some charts and updating the dashboard title.

/cc @blockloop 
/assign @ewolinetz 

image

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
@mburke5678 Mike, this PR will bring the Elasticsearch dashboard in sync with the latest documentation.

**Review by blockloop — CHANGES_REQUESTED** [review]
Can you add a screenshot of the new dashboard and explain the changes in the description, please?

**Comment by mburke5678** [comment]
@lukas-vlcek @ewolinetz How are these changes planned to be introduced? Using a z-stream?

**Comment by ewolinetz** [comment]
@mburke5678 currently with this PR it will go in with out as 4.7 since its going into master

**Comment by lukas-vlcek** [comment]
@blockloop The screenshot is the same one that is attached to https://issues.redhat.com/browse/LOG-700
It did not change. For some reason we got into the repo some older version of the dashboard. This PR brings in the same version of dashboard that is in LOG-700.

As for the naming I would refer to communication I had with @sichvoge (it is buried deep in Slack).

@ewolinetz In fact this should really go to 4.6 if possible asap.

**Pull request merged**
