### PR TITLE
manifests: make file structure version-agnostic

### PR DESCRIPTION
**Pull request by sosiouxme**
I'd like to try removing the version from the file/directory structure now that we're building bundles in 4.6. There is no real need for it as far as I can see, and this will mean we no longer have to update the structure at branch cut before we (ART) can build anything. It will also mean you can cherry-pick fixes between branches more sanely.

It will require a corresponding ART config change which I'll handle. If it works out (I've tested as far as I can yet), I'll ask everyone to do this instead of updating their directories 4.5 => 4.6.

### CODE REVIEW

**Comment by ewolinetz** [comment]
/approve
it doesn't seem like this would break any of our ci, i'll wait for a second set of eyes

**Comment by bparees** [comment]
it seems reasonable to me.  @shawn-hurley any concerns?

**Comment by periklis** [comment]
@sosiouxme Since we are change the filesystem structure to close the gap to operator bundle for OLM. WDYT of switching to the OLM directory structure, e.g.:

**Comment by sosiouxme** [comment]
reorganizing is fine, but we need to keep at least some things that the ART process looks at (package.yaml, art.yaml, image-references). let me look into this a bit.

**Comment by periklis** [comment]
> reorganizing is fine, but we need to keep at least some things that the ART process looks at (package.yaml, art.yaml, image-references). let me look into this a bit.

For sure we need to keep these files for ART. One reason I pointed to the OLM file structure is that `operator-sdk` is assuming it. So basic development tasks need less copy workarounds, e.g. `operator-sdk generate crds` lands the crds in the `deploy/crds` folder. (cc @alanconway That might be interesting for your LF GA cleanup to avoid double work).

**Comment by jcantrill** [comment]
> reorganizing is fine, but we need to keep at least some things that the ART process looks at (package.yaml, art.yaml, image-references). let me look into this a bit.

@sosiouxme any reason the art specific files could not live in `deploy`?

**Comment by sosiouxme** [comment]
yeah... ignore this until i know what i'm talking about.

**Pull request closed without merging**
