### PR TITLE
LOG-887: part-1: upgrade operator-sdk to v0.19.4 in go module

### PR DESCRIPTION
**Pull request by huikang**
- Upgrade operator-sdk to v0.19.v

### Description
Following the [instruction](https://sdk.operatorframework.io/docs/building-operators/golang/migration/#migration-steps): this PR upgrade the operator-sdk to the next stable release version(v0.19.4).

Quote: Note: It is recommended that you have your project upgraded to the latest SDK release version before following the steps of this guide to migrate to new layout.

/cc @ewolinetz 
/assign @periklis 

### Links
- JIRA: https://issues.redhat.com/browse/LOG-887

### CODE REVIEW

**Review by periklis — COMMENTED** [review]
LGTM, but I would like to stress the point that usually an operator-sdk version updates goes hand in hand with updating the `k8s.io` deps e.g. `client-go` to the corresponding version:
- operator-sdk 0.18 -> k8s 1.18

Have you been able to conclude that the operator-sdk project stopped following this practice in 0.19?

**Comment by huikang** [comment]
@periklis , thanks for the comment. I did remember I read somewhere (operator-sdk or kubebuilder) says something about required changes to the import, but somehow I could not find that link. (If you have that, could you paste the link?)

So I check the go module operator-sdk v0.19.4 and find they seem still use 0.18: https://github.com/operator-framework/operator-sdk/blob/125d0dfcc71fef4f9d7e2a42b1354cb79ffdee03/go.mod#L40-L49

**Comment by huikang** [comment]
\retest

**Comment by periklis** [comment]
> @periklis , thanks for the comment. I did remember I read somewhere (operator-sdk or kubebuilder) says something about required changes to the import, but somehow I could not find that link. (If you have that, could you paste the link?)
> 
> So I check the go module operator-sdk v0.19.4 and find they seem still use 0.18: https://github.com/operator-framework/operator-sdk/blob/125d0dfcc71fef4f9d7e2a42b1354cb79ffdee03/go.mod#L40-L49
> 
> **EDIT**: The v1.1.x uses k8s 0.18: https://github.com/operator-framework/operator-sdk/blob/5deb5e6b17df8209c6a003c628bb84c773e4ee05/go.mod#L28-L33
> 
> So operator-sdk seems stop following the practice **since 0.19**.

FYI, the following `go.mod` [template](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugin/v3/scaffolds/internal/templates/gomod.go) used to be in the operator-sdk repository. It used to reference the required minimum k8s version (e.g. [sdk 0.18 example](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v0.18.0/#modules)) for generated projects by the operator-sdk CLI. Since operator-sdk merged with kubebuilder, the template moved upstream as well. 

Thus, the new way to check if we need to bump our k8s dependencies is the following:
1. Pick operator-sdk version, e.g. 0.19
2. [Identify kubebuilder version referenced by operator-sdk](https://github.com/operator-framework/operator-sdk/blob/v0.19.x/go.mod#L53)
2. [Identify controller-runtime version referenced by kubebuilder](https://github.com/kubernetes-sigs/kubebuilder/blob/36aa113dbe99a7bdd883d42f8545468a2017775d/pkg/plugin/v3/scaffolds/init.go#L38)
3. [Check controller-runtime's go.mod file](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.6.0/go.mod#L28)

Following this practice I can confirm your thesis that operator-sdk **0.19** is pinned to kubernetes **1.18.2** through controller-runtime **0.6.0**.

I believe this practice should be documented in our HACKING.md under the docs folder, to enable everybody update the SDK in the future. WDYT? Would you mind to add this docs to this PR please?

**Comment by huikang** [comment]
> I believe this practice should be documented in our HACKING.md under the docs folder, to enable everybody update the SDK in the future. WDYT? Would you mind to add this docs to this PR please?

Thanks for digging deeper into this.
I agree and am willing updating the doc with those info.

**Comment by periklis** [comment]
Thank you, will drop the hold and put the LGTM again once you have updated the docs.

**Pull request merged**
