### PR TITLE
Log 2342: Kibana certificates update when ca secret is recreated

### PR DESCRIPTION
**Pull request by Red-GV**
### Description
Adding the CA secret to the list of secrets for the Kibana Controller to watch. Without this, the controller will not reconcile if the CA secret is recreated and Kibana will not be able to communicate with Elasticsearch. With the PR, the controller will restart the pod with the appropriate certificates.

/cc @sasagarw 
/assign @periklis 

### Links
- JIRA: https://issues.redhat.com/browse/LOG-2342

### CODE REVIEW

**Comment by periklis** [comment]
Looking at this change make me wonder how the two controller loops (elasticsearch, kibana) handle the order of events avoiding race conditions safely. For sanity reasons, I will outline my understanding below and if I am wrong I am happy to approve this change. 

AFAIU the eo-cert-management generation is split into both controller loops, i.e.
- `elasticsearch-controller` triggers `GenerateElasticsearchCerts`
- `kibana-controller` triggers `GenerateKibanaCerts`

Both loops ensure that a valid signing CA `signing-$NAME_OF_ES_CR_HERE` exists before generating any certificates. However both loops the Elasticsearch CR as the single only OwnerRef for the generated certificates. Means besides elasticsearch related certs, the secrets holding the `kibana` and the `kibana-proxy` are owned by the `Elasticsearch` CR.

From here on starts my confusion with the approach taken by this pull request. According to the proposed changes the kibana controller will handle secret updates events for a secret that the Kibana CR is not owning. The typical chain of responsibility for every controller is `CR -> Owned objects` to keep controller loops independent. In this change the kibana controller loop dependents on events for objects **not** owned by the controlled Kibana CR. In addition the content of the secrets a.k.a. certificates are bound by a validation time range that adds up to the complexity.

FWIW, I suggest to try to keep the loops independent from each other. I propose to use a hash in an annotation on the Kibana CR that is propagated down to the Kibana's pod templace spec to initiate the restart when the signing CA changes. The timeline of events would look like this:
- The elasticsearch-controller reconciles every 30s the generation of certs.
- If certs or CA are invalid it triggers the generation of CA and certs anew.
- A new hash for the CA contents is generated if the CA changes.
- This CA hash is stored on the Elasticsearch CR as an annotation.
- The kibana-controller reconciles every 30s (New Change)
- The kibana-controller reads the ES CR either way to pull the CR name (Present behavior) and the CA hash (New Change).
- It compares the CA Hash from the ES CR with a hash on the Kibana CR.
  - If hashes are equal, `GenerateKibanaCerts` is not triggered.
  - If hashes **not** equal, `GenerateKibanaCerts` is triggered.

WDYT? (cc @xperimental )

**Comment by Red-GV** [comment]
@periklis Actually, just having the Kibana controller reconcile ever 30 seconds will solve the issue. The work done in #849 already detects changes in the CA and trigger the certs to be regenerated when the signing no longer matches.

**Pull request merged**
