### PR TITLE
LOG-968: fix lint issues

### PR DESCRIPTION
**Pull request by blockloop**
### Description
Fix lint errors from `make lint`

/cc @periklis 
/assign @jcantrill

### CODE REVIEW

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by blockloop** [comment]
@periklis I'll need another lgtm here because I had to remove it from the build target
@jcantrill please take a look whenever you get a chance

**Review by periklis — APPROVED** [review]
/lgtm

**Review by jcantrill — COMMENTED** [review]
/approve

**Pull request merged**
