### PR TITLE
Bug 1878123: Bump client-go v1.18.3 to v1.18.8

### PR DESCRIPTION
**Pull request by periklis**
### Description
This PR addresses an emergency bump for client-go from version v1.18.3 to v1.8.8 to include the following fix:
https://github.com/periklis/elasticsearch-operator/pull/new/bz-1878123

Further discussion: https://post-office.corp.redhat.com/archives/aos-devel/2020-September/msg00177.html

/cc @ewolinetz @lukas-vlcek

### CODE REVIEW

**Comment by ewolinetz** [comment]
@periklis do we have any reports of this error for our operator?

**Comment by periklis** [comment]
> @periklis do we have any reports of this error for our operator?

Not for our operator, but following the "action required" voice in aos-devel, we may hit this soon.

**Pull request merged**
