### PR TITLE
LOG-824: tidy receiver names and gofumports

### PR DESCRIPTION
**Pull request by blockloop**
### Description
Just some gofumports and lint tidy

/cc @periklis 
/assign @ewolinetz

### CODE REVIEW

**Review by periklis — CHANGES_REQUESTED** [review]
LGTM, missing gofumports in Makefile `go fmt` target.

**Comment by blockloop** [comment]
> LGTM, missing gofumports in Makefile `go fmt` target.

Okay, but you asked for it :D

**Pull request merged**
