### PR TITLE
[WIP] SDK bump from v0.0.7 => v0.7.0

### PR DESCRIPTION
**Pull request by ewolinetz**
Being done following : https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/v0.1.0-migration-guide.md

### CODE REVIEW

**Comment by ewolinetz** [comment]
Currently the code passes unit tests but looks like spaghetti. I'm going to try to restructure our code so we don't have to pass a client around all over.
(Also need to fix up e2e test -- we register with the framework differently)

**Comment by jcantrill** [comment]
> Currently the code passes unit tests but looks like spaghetti. I'm going to try to restructure our code so we don't have to pass a client around all over.
> (Also need to fix up e2e test -- we register with the framework differently)

The type should either be wrappered similar to what we did for CLO or the client should be set on the struct or the thing that is already passed around everywhere

**Comment by richm** [comment]
does this PR obsolete https://github.com/openshift/elasticsearch-operator/pull/57 ?

**Comment by ewolinetz** [comment]
@richm yes

**Comment by ewolinetz** [comment]
Currently seeing `no kind is registered for the type v1.ServiceMonitor in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:61\"` in the operator logs. asking sdk group about this since it looks like it should be added to the scheme (unless its a sdk version issue)

**Comment by richm** [comment]
> Currently seeing `no kind is registered for the type v1.ServiceMonitor in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:61\"` in the operator logs. asking sdk group about this since it looks like it should be added to the scheme (unless its a sdk version issue)

Maybe it isn't `v1`?  I know there are some other types that aren't yet v1 e.g. `subscriptions.operators.coreos.com/v1alpha1`

**Comment by ewolinetz** [comment]
@richm the issue ended up being that we needed to add the prometheus monitoring scheme to ours for the sdk. Once i added that in `cmd/manager/main.go` it rectified it

**Comment by ewolinetz** [comment]
I just realized that I copied over code from a bad starting point.. i'm going to close this PR for now and reopen it when I fix it so that we aren't constantly getting CI errors emailed out

**Pull request closed without merging**
