### PR TITLE
Bug 1894632: Add ES-Proxy Resources to Elasticsearch CR

### PR DESCRIPTION
**Pull request by vimalk78**
### Description
Cherry pick of changes for fixing bug 1856502
 including the fix "Fixing rollout detection, settings being overwritten mid update, and function call ordering"

/cc @blockloop @periklis 
/assign @jcantrill 

### Links
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1856502

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/approve

**Review by periklis — APPROVED** [review]
/lgtm

**Pull request merged**
