### PR TITLE
updating bundle labels to be used for nightly

### PR DESCRIPTION
**Pull request by ewolinetz**
Updating bundle labels per:
* https://docs.engineering.redhat.com/display/CFC/Migration

### CODE REVIEW

**Comment by ewolinetz** [comment]
/hold cancel
@jcantrill we'll want the same changes for CLO so it can be part of the nightly builds

**Review by periklis — APPROVED** [review]

**Comment by jcantrill** [comment]
overriding labels to fix bundles for nightly builds

**Pull request merged**
