### PR TITLE
Delete readiness probe

### PR DESCRIPTION
**Pull request by josefkarasek**

### CODE REVIEW

**Comment by josefkarasek** [comment]
@jcantrill we wanted to remove the probe, or not?

**Comment by jcantrill** [comment]
> @jcantrill we wanted to remove the probe, or not?
We may have to hold on this PR until we migrate the `init` logic out of the ES image.  We do want to remove the probe but this also implies the operator determines 'ready'.  I believe when @ewolinetz initially discussed this we talked about enabling/disabling the `logging-es` service so it blocks traffic until ES is ready; 'ready' is currently after all the `init` scrips complete.  

We have not fully discussed if the `cluster-logging-operator` or `elasticsearch-operator` should hold this logic.  One could say the `elasticsearch-operator` but I believe then we need to devise an abstraction where one declares the image to use for initialization.  This is the approach I would prefer but I think @ewolinetz idea was to move all the 'init' logic directly into the operator.  I don't believe we are ready yet and should capture final decisions in https://jira.coreos.com/browse/LOG-216

**Comment by ewolinetz** [comment]
> We have not fully discussed if the cluster-logging-operator or elasticsearch-operator should hold this logic. One could say the elasticsearch-operator but I believe then we need to devise an abstraction where one declares the image to use for initialization. This is the approach I would prefer but I think ewolinetz idea was to move all the 'init' logic directly into the operator. I don't believe we are ready yet and should capture final decisions in https://jira.coreos.com/browse/LOG-216

My thought is that it would live in the ES operator since this would allow us to make the Elasticsearch image we provide lighter and we can take a more elegant approach to seeding/initializing if we have it within the operator so we can be sure we only perform it when necessary per cluster instead of every time an ES pod starts up.

**Comment by ewolinetz** [comment]
For now we want to keep the Readiness Probe. If we were going to remove it we need to have the operator control the logic on the 9200 port SVC where it does and doesn't map to the Elasticsearch pods when appropriate.

**Pull request closed without merging**
