### PR TITLE
[WIP] feat(scripts): add percent script

### PR DESCRIPTION
**Pull request by georgettica**
DISCALIMER: I am new to `elasticsearch-operator` I just created the script and used parts of the code from the `delete` job.

Goals:
- targeted to  ES6 (OCP4.5 and up)
- deletion will be based on PolicyMapping ( all indices under that alias )
- similar operation to the `delete` script

Non-Goals:
This proposal is **not** a clusterwide deletion of indices

The proposed CRD schema I suggest:
```
spec:
  indexManagement:
    policies:
    - name: infra-policy
      pollInterval: 1m
      phases:
        hot:
          actions:
            rollover:
              maxAge:   2m
        delete:
          minAge: 5m
          maxUtilization: 20 // This should be in a percentage
```

How the script is implemented so far:

1. Get indices from PolicyMapping (same as `delete`)
0. Get write index (same as `delete`)
0. Get cluster size
0. Get indices in reverse order  (same as `delete`)
0. Join with indices based on size
0. take indices until the threshold is passed
0. Delete indices  (same as `delete`)

this currently is working on all of the cluster resources (aka `_nodes/stats/os`) but could be reformatted to a different format if wanted

the drawback is that if there is a single index consuming all of the data it will be deleted and no data will remain in ES

Things left to do:
- [ ] add CR support to this operation
- [ ] decide how the percentage cronjobs will be set to avoid race condition

### CODE REVIEW

**Comment by jcantrill** [comment]
/nack

As stated in a thread from @lukas-vlcek , IndexManagement is loosely based upon OpenDistro and their available options which we intend to embrace once we move to a newer version.  Also, IM is based on evaluating individual indices and not storage as a whole.  I would agree with his proposal there should be some action taken as a result of an alert that curates the entire storage and not an individual set of indices.  If disk is filling up that exceeds IndexManagement then:
* Re-evaluation of the cluster logging should be done to ensure enough space is available
* Retention should be reduced
* Redundancy should be modified
* The operator should take action to correct

@ewolinetz there is likely something here with regards to a level 5 operator that should be taken into account

**Comment by periklis** [comment]
> ... Also, IM is based on evaluating individual indices and not storage as a whole. I would agree with his proposal there should be some action taken as a result of an alert that curates the entire storage and not an individual set of indices.

@jcantrill @lukas-vlcek  I don't quite understand why the difference (single vs. multiple indices) applies only for the proposed policy vs. what we have today with `maxAge`. We do for both batch index deletions. Let me put some examples on how both translate here:
1. **maxAge**: Applies per policy mapping and tells IM: `Delete all indices of a policy mapping (e.g. infra-write -> infra-xxxxxx) that are older than maxAge`.
2. **maxUtilization**: Applies per policy mapping and tells IM: `Delete all indices of a policy mapping (e.g. infra-write -> infra-xxxxxx) so that total space used by this policy mapping is not higher than maxUtilization`

The policy proposed here is a retention policy based on disk usage caps, which is common in other products.

**Comment by ewolinetz** [comment]
> @jcantrill @lukas-vlcek I don't quite understand why the difference (single vs. multiple indices) applies only for the proposed policy vs. what we have today with `maxAge`. We do for both batch index deletions. 

I think the concern is more around us implementing functionality that is not also in Opendistro, which will make it harder for us to simply use their index management in the future.
https://opendistro.github.io/for-elasticsearch-docs/docs/ism/policies/#transitions

**Comment by georgettica** [comment]
closing this as a different effort is in place, thanks all for your time and effort on this

**Pull request closed without merging**
