### PR TITLE
Move generated CRDs to the OCP versioned target manifest folder

### PR DESCRIPTION
**Pull request by periklis**
### Motivation
Besides the elasticsearch-operator project using the operator-sdk to generate code and CRDs it doesn't clearly adhere to the operator-sdk project structure. Thus, this PR extends the Makefile to move generated CRDs to the target manifest folder.

Depends on #277

### CODE REVIEW

**Comment by jcantrill** [comment]
@alanconway Doesn't your equivalent to CLO remove operator-sdk generated manifests?  I think this PR is in the wrong direction

**Comment by periklis** [comment]
@jcantrill The PR applies the same as https://github.com/openshift/cluster-logging-operator/pull/413/files#diff-b67911656ef5d18c4ae36cb6741b7965R76

**Comment by periklis** [comment]
We concluded in our arch meeting to not use this approach. Thus I close this PR.

**Pull request closed without merging**
