### PR TITLE
Migrate operator-sdk and deps to v0.18.1

### PR DESCRIPTION
**Pull request by periklis**
### Motivation
Based on the [operator-sdk upgrade guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md) this PR updates the dependencies and adapts to breaking changes for operator-sdk@v0.18.0.

This PR enables the operator to use k8s v1.18.3 and in turn openshift release-4.6

**Depends on:** ~#290 and openshift/release#7849~

### CODE REVIEW

**Comment by igor-karpukhin** [comment]
@periklis  lgtm, but needs to be rebased first

**Comment by periklis** [comment]
@jcantrill PTAL a look again to ensure landing this for 4.6.

**Comment by ewolinetz** [comment]
/approve cancel
i don't think we should have api version bumps as part of this -- the pr talks about sdk and dep bump, lets keep it to just that. i think there are additional things to consider when bumping our api object versions

**Pull request merged**
