### PR TITLE
Bug 1844329: Stop reconciliation on ES CR not present

### PR DESCRIPTION
**Pull request by periklis**
### Description
This is a manual cherry-pick of #370 as the auto-created cherry-pick #380 has merge conflicts.

/cc @ewolinetz @blockloop

### CODE REVIEW

**Comment by periklis** [comment]
@sdodson Can we pick this for the next 4.5 z-stream? It eliminates some confusion in customer cases and makes troubleshooting less prone to false negatives.

**Comment by sdodson** [comment]
@periklis I'm not patch manager right now, please see the docs linked from #forum-release topic for more info on the process.

**Comment by periklis** [comment]
@derekwaynecarr Can we pick this for the next 4.5 z-stream? It eliminates some confusion in customer cases and makes troubleshooting less prone to false negatives.

**Comment by markmc** [comment]
> @derekwaynecarr Can we pick this for the next 4.5 z-stream? It eliminates some confusion in customer cases and makes troubleshooting less prone to false negatives.

(patch manager here) Skipping for now since we have quite a lot of changes already for this release and this issue has low user-impact

**Comment by sdodson** [comment]
Hmm, the bug has been closed wontfix.
/bugzilla refresh

**Pull request closed without merging**
