### PR TITLE
Log-1100: Warning alerts to prevent users from reaching disk watermark thresholds

### PR DESCRIPTION
**Pull request by sasagarw**
### Description

This PR:
- Adds warning alert for low, high and flood disk watermark thresholds
- The thresholds are predicted by taking data of past 3h and alerted if it is expected to cross the threshold within next 6h
- To avoid false positives, the alert will be fired only if it stays active for 1h
- Added unit test to verify the alert
- Added playbook for low disk watermark

/cc @lukas-vlcek 
/assign @ewolinetz 

### Links
- JIRA: https://issues.redhat.com/browse/LOG-1100

### CODE REVIEW

**Comment by ewolinetz** [comment]
/approve
@lukas-vlcek @blockloop can you please review for content?

**Review by blockloop — APPROVED** [review]
/lgtm

**Pull request merged**
