### PR TITLE
Fixing upgrade test failures

### PR DESCRIPTION
**Pull request by ewolinetz**
### Description
Attempting to fix up rehearsal errors on https://github.com/openshift/release/pull/13502
```
/go/src/github.com/openshift/elasticsearch-operator/hack/testing-olm-upgrade/upgrade-common: line 153: log::info: command not found
/go/src/github.com/openshift/elasticsearch-operator/hack/testing-olm-upgrade/upgrade-common: line 29: log::info: command not found 
```

### CODE REVIEW

**Comment by ewolinetz** [comment]
looks like https://github.com/openshift/elasticsearch-operator/pull/564 broke this... 
need to pivot and do a partial revert

**Comment by periklis** [comment]
> looks like #564 broke this...

This is really unfortunate and unintentional. I removed the duplicates from the `utils` file in favour of `os::cmd::expect..` and `os::log::info...` because they can be used to compile a junit report. Why not use these also in the upgrade tests instead of adding the duplications back?

**Comment by ewolinetz** [comment]
> This is really unfortunate and unintentional. I removed the duplicates from the `utils` file in favour of `os::cmd::expect..` and `os::log::info...` because they can be used to compile a junit report. Why not use these also in the upgrade tests instead of adding the duplications back?

I can make the changes to use `os::log::info` instead, however the `expect` changes I'd prefer to do as tech debt

**Comment by periklis** [comment]
> > This is really unfortunate and unintentional. I removed the duplicates from the `utils` file in favour of `os::cmd::expect..` and `os::log::info...` because they can be used to compile a junit report. Why not use these also in the upgrade tests instead of adding the duplications back?
> 
> I can make the changes to use `os::log::info` instead, however the `expect` changes I'd prefer to do as tech debt given it is a bit more involved and my intention was to fix the broken test

What is the difference with the `expect` statements? Using `os::cmd::expect` is not a big thing that we should postpone to tech debt.

**Review by periklis — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
