### PR TITLE
Bug 1765808: Add subject per ES instance to es-proxy cluster role binding

### PR DESCRIPTION
**Pull request by pavolloffay**
Port of https://github.com/openshift/elasticsearch-operator/pull/193 for 4.2

https://bugzilla.redhat.com/show_bug.cgi?id=1765808
https://issues.jboss.org/browse/OSSM-100

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by ewolinetz** [comment]
See comments on https://github.com/openshift/elasticsearch-operator/pull/195

**Comment by pavolloffay** [comment]
@ewolinetz added comments

**Comment by pavolloffay** [comment]
@richm @nhosoi could you please approve this PR?

**Comment by richm** [comment]
lgtm - this is just a cherrypick, right?

**Comment by pavolloffay** [comment]
@richm @jcantrill can you add cherry-pick-approved label to satifly the bot?

**Comment by richm** [comment]
> @richm @jcantrill can you add cherry-pick-approved label to satifly the bot?

No, it must be done by the patch manager.

**Comment by derekwaynecarr** [comment]
/bugzilla refresh

looks like the referenced bug in 4.3 is still ON_QA

**Pull request merged**
