### PR TITLE
Update operator-sdk to v1.19.1

### PR DESCRIPTION
**Pull request by btaani**
### Description
This PR updates operator-sdk to v1.19.1 since the previously used version (v1.18.1) caused `make bundle` to fail with the following error:

> FATA[0000] Error generating bundle manifests: could not find manager deployment, should have label control-plane=controller-manager 

Original bug report: https://github.com/operator-framework/operator-sdk/issues/5574

/cc @xperimental 
/assign @periklis 

### Links
- JIRA: [LOG-2490](https://issues.redhat.com/browse/LOG-2490)

### CODE REVIEW

**Comment by xperimental** [comment]
Have you run `make bundle` after the update already? I think this might make changes to the bundle.

**Comment by btaani** [comment]
@xperimental I just did

**Pull request merged**
