### PR TITLE
Bug 1946772: fix es crd status incompatible when upgrading operator

### PR DESCRIPTION
**Pull request by Red-GV**
Manual cherrypick of: #686

Fix crd incompability during upgrading from 4.5 to 4.6

/assign @ewolinetz

### CODE REVIEW

**Comment by ewolinetz** [comment]
@Red-GV can you please update the commit message to provide context as to what this changes?

**Comment by mfojtik** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.


* Score: *0.20*
* Reason: *maximum total for this z-stream is 10*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Pull request merged**
