### PR TITLE
[release-5.5] Remove from stable channel

### PR DESCRIPTION
**Pull request by periklis**
### Description
Removes the stable channel pointer to release-5.5. This is due to releasing 5.6 soon.

Depends on:

* https://github.com/openshift/release/pull/34494

/cc @jcantrill 
/assign @jcantrill

### CODE REVIEW

**Comment by periklis** [comment]
@jcantrill I created this PR early on for visibility. We will need to release this together with the first 5.5.z stream after 5.6.0 is out.

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Pull request merged**
