### PR TITLE
Use origin- prefix for quay.io image references

### PR DESCRIPTION
**Pull request by periklis**

### CODE REVIEW

**Comment by jcantrill** [comment]
This reverts some of #258 because we mirror using origin https://github.com/openshift/release/blob/master/core-services/image-mirroring/openshift/mapping_origin_4_5#L87

**Comment by periklis** [comment]
@jcantrill Correct. We missed that the base prefix is give by the generation target in https://github.com/openshift/release/blob/master/core-services/image-mirroring/openshift/Makefile#L13

**Pull request merged**
