### PR TITLE
[release-4.6] Bug 1901756: Handle invalid json input in delete script

### PR DESCRIPTION
**Pull request by huikang**
### Description
Manual fixing cherry-pick #588 

    - take multiple lines of input
    - report error message instead of trackback

/cc @ewolinetz @alanconway 
/assign  @ewolinetz

/cherry-pick release-4.5

### Links
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1901756

### CODE REVIEW

**Review by alanconway — COMMENTED** [review]
The change looks correct to me but the whole thing is hurting my brain: a Go program that produces a bash script that produces ruby scripts that somebody eventually runs? Just trying to read all 3 languages at once is painful. Can we write a single program, in a single language that does the job? Go has JSON parsing, it can read and write files and execute commands. Why the unholy threesome?

**Comment by huikang** [comment]
@alanconway , thanks for your feedback. I agreed the script needs to be simplified into a single language. Given that the customer is asking the ETA for the for the 4.5 and 4.6 (https://bugzilla.redhat.com/show_bug.cgi?id=1899905#c9), so lgtm?
We may create a jira card to improve the script for next release. 

@ewolinetz, what do you think ?

**Comment by ewolinetz** [comment]
/hold
this needs to follow the correct process, have already discussed next steps for this on slack

**Pull request closed without merging**
