### PR TITLE
Bug 1906895: Fixing lost changes in 4.7 csv and adding 5.0 csv for disconnecting from ART

### PR DESCRIPTION
**Pull request by ewolinetz**
### Description
To unblock disconnect from ART

/cc @vimalk78 @blockloop @periklis 

### Links
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1906895

### CODE REVIEW

**Review by periklis — CHANGES_REQUESTED** [review]
@ewolinetz Please consult with @huikang on how to change manifest version via `Makefile` and simple changes in the new `config` top-level directory w/o the need to move files in the `manifests` directory. Such changes are nowdays automated by the operator-sdk.

**Comment by periklis** [comment]
> /retest

@jcantrill 
Please don't hit simply retest. The PR is needs some re-work first.

**Comment by ewolinetz** [comment]
> w/o the need to move files in the manifests directory

the purpose of this PR is to create a `5.0` manifest directory and remove the `4.7` one

**Comment by periklis** [comment]
> > w/o the need to move files in the manifests directory
> 
> the purpose of this PR is to create a `5.0` manifest directory and remove the `4.7` one

The point of my down-thumbed query is that you don't need to create this folder any more by manually moving files. 

The only steps you need to take since @huikang introduced the new kubebuilder format are:
1. Update the Makefile variable `OCP_VERSION` to `5.0`
2. Update the new manifest base [config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml](https://github.com/openshift/elasticsearch-operator/blob/master/config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml#L101)
3. Execute `make bundle`, which generate the bundle dir and old manifests dir contents.
4. Adapt the oldschool ART files `manifests/art.yaml` and `manifests/elasticsearch-operator.package.yaml`

Result looks like this:
image

I've done this exercise myself when writing the above and the `make bundle` still suffers from one issue:
- Remove the `manifests/4.7` and create an empty `manifests/5.0` yourself.

Easy to add a fix in this PR.

**Comment by jcantrill** [comment]
> > > w/o the need to move files in the manifests directory
> > 
> > 
> > the purpose of this PR is to create a `5.0` manifest directory and remove the `4.7` one
> 
> The point of my down-thumbed query is that you don't need to create this folder any more by manually moving files.
> 
> The only steps you need to take since @huikang introduced the new kubebuilder format are:
> 
>     1. Update the Makefile variable `OCP_VERSION` to `5.0`

This may be the path for our long term direction but is not the point to solve the immediate needs.  This image currently is still being built by both ART and CPaaS.  We require both because of the dual workflows.  Duplicates allow us to have the latest images and for the CPaaS work to continue until such time we can disconnect from ART.  The intention is to converge on a single manifest when we fully disconnect.

**Review by periklis — COMMENTED** [review]
/lgtm

**Pull request closed without merging**
