### PR TITLE
LOG-1169: Fix no icon on EO in Operator Hub

### PR DESCRIPTION
**Pull request by vimalk78**
### Description
[LOG-1169](https://issues.redhat.com/browse/LOG-1169): Fix no icon on EO in Operator Hub
   - Changed image type from `image/svg` to `image/svg+xml`
   
/cc 
/assign @ewolinetz 

/cherry-pick master

### Links

- JIRA: https://issues.redhat.com/browse/LOG-1169

### CODE REVIEW

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by vimalk78** [comment]
> /hold @vimalk78 You should now update the CSV neither in the `bundle` nor in the `manifests` directory for EO. The approach is to update the CSV `config/manifests/bases` and execute `make bundle`.

Updated

**Review by periklis — COMMENTED** [review]
/lgtm

**Pull request merged**
