### PR TITLE
LOG-910: Add unit test validation for Prometheus rules and alerts

### PR DESCRIPTION
**Pull request by lukas-vlcek**
Introducing a new makefile target to lint prometheus rules files.

/cc @periklis

### CODE REVIEW

**Review by periklis — COMMENTED** [review]
It looks overall good to me. In addition I would like to raise the following question to all (cc @blockloop @ewolinetz ).

Why don't we go one step further using the `unit testing` facility of promtool?
https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/

AFAIU, you can inject hardcoded series data and unit test your rules. Right?

**Comment by ewolinetz** [comment]
@periklis we could, but that is currently outside the scope of what the jira card this addresses covers. I think it would be useful to expand on this further to also add the unit testing as a follow up. I'll create a card to track that work for us

**Pull request merged**
