### PR TITLE
LOG-887: part-2: new layout, type, controller with operator-sdk 0.19

### PR DESCRIPTION
**Pull request by huikang**
### Description

    - update ./hack/generate-crd.sh to generate code using
      controller-gen
    - move apis to root directory
    - move controller to root directory
    - add RBAC permission in go code
    - move main.go to root directory
    - (TODO):
       1. how to integrate into bundle/manifests
       2. copy generated CRD, RBAC to MANIFESTS_DIR

/cc @ewolinetz 
/assign @periklis @blockloop 

/cherry-pick 

### Links

- Depending on PR(s): https://github.com/openshift/elasticsearch-operator/pull/554
- JIRA: https://issues.redhat.com/browse/LOG-887

### CODE REVIEW

**Comment by huikang** [comment]
Leave this as open as a reference for #566

**Comment by periklis** [comment]
@huikang We can close this PR in favor of #566 right?

**Comment by ewolinetz** [comment]
closing in favor of https://github.com/openshift/elasticsearch-operator/pull/566

**Pull request closed without merging**
