### PR TITLE
Updating EO to use operator bundle

### PR DESCRIPTION
**Pull request by ewolinetz**
Generated using `make generate-bundle`

To address changes required as part of https://issues.redhat.com/browse/OLM-1810

### CODE REVIEW

**Comment by periklis** [comment]
> This is exactly the content of bundle container in dist-git
> http://pkgs.devel.redhat.com/cgit/containers/elasticsearch-operator-bundle/tree/?h=rhaos-4.6-rhel-7
> 
> this is exactly what is supposed to be generated using `render_templates` in cpaas build. especially updating the `spec.relatedImages` fields in CSV

So we may drop the dist-git stuff then? Creating the bundle with the operator-sdk sounds more natural to me than using extra bash/python/whatever tooling.

**Comment by ewolinetz** [comment]
we're being asked to move to operator bundles as part of work being done here: https://issues.redhat.com/browse/OLM-1810

**Comment by vimalk78** [comment]
> So we may drop the dist-git stuff then?

we probably cannot. we need to update the CSVs with the correct image SHAs, release number etc taken from brew build info.

need to understand little deeply how these two things fit together. perhaps dist-git content will be populated using `make generate-bundle` ?

**Comment by periklis** [comment]
> > So we may drop the dist-git stuff then?
> 
> we probably cannot. we need to update the CSVs with the correct image SHAs, release number etc taken from brew build info.
> 

@vimalk78 Can we at least limit the dist-git stuff to only update the correct image SHAs instead of generating this whole bundle?

IMHO the bundle work will be probably also making it into our olm-deploy approach for running E2E tests. I would rather have this under our control in this repository instead of some gitlab repository our downstream CI.

**Comment by ewolinetz** [comment]
/retest
silly sticky 'e' key :-/

**Pull request merged**
