### PR TITLE
remove EO from CVO build pipeline

### PR DESCRIPTION
**Pull request by jcantrill**
remove EO from CVO build pipeline

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @bparees

**Comment by josefkarasek** [comment]
@jcantrill can you pls point me to some documentation for these labels?

**Comment by jcantrill** [comment]
@josefkarasek I can only point you to the CVO document which does not describe much other then the CVO pipeline

**Comment by jcantrill** [comment]
cc @bparees

**Comment by ewolinetz** [comment]
can we fold this into #101? seems this is part of a similar fix

**Comment by bparees** [comment]
> @josefkarasek I can only point you to the CVO document which does not describe much other then the CVO pipeline

The OLM labels were mentioned in Tim Bielawa's email, " Should YOUR operator be in the OpenShift Marketplace? Action required if you think "YES""

but @jwforres also has a doc that's nearly ready which covers this topic in more detail.

**Pull request merged**
