### PR TITLE
Bug 1752073: Increased operator-sdk version to 0.8.2

### PR DESCRIPTION
**Pull request by igor-karpukhin**
Changed operator SDK version from 0.7.0 to 0.8.2

### CODE REVIEW

**Comment by jcantrill** [comment]
@igor-karpukhin Please title this like `Bug XXXXX:  Some description` so the bot will manage the state of the associated bz

**Comment by igor-karpukhin** [comment]
@richm could you please take a look? I fixed the failing test

**Comment by ewolinetz** [comment]
we should have squashed the commits fyi...

**Pull request merged**
