### PR TITLE
Removed a target namespace recommendation from the CSV

### PR DESCRIPTION
**Pull request by syedriko**

### CODE REVIEW

**Comment by periklis** [comment]
Found the same recommendation in the ClusterServiceVersion:
https://github.com/openshift/elasticsearch-operator/blob/master/manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml#L9

**Comment by syedriko** [comment]
> Found the same recommendation in the ClusterServiceVersion:
> https://github.com/openshift/elasticsearch-operator/blob/master/manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml#L9

Right, I'm wondering if InstallModes https://github.com/openshift/elasticsearch-operator/blob/b6c6d9e299bb4a6e62dc6d76c0078245c8c599ee/manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml#L108 need fixing. @jcantrill ?

**Pull request merged**
