### PR TITLE
Bug 1725249: Updating to not set CPU limit unless it is explicitly set

### PR DESCRIPTION
**Pull request by ewolinetz**
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1725249

Cherry pick of:
* https://github.com/openshift/elasticsearch-operator/pull/170
* https://github.com/openshift/elasticsearch-operator/pull/160

Combination of:
* https://github.com/openshift/elasticsearch-operator/pull/172 
* https://github.com/openshift/elasticsearch-operator/pull/163

### CODE REVIEW

**Comment by jwforres** [comment]
QE has validated the fix for this in 4.2 at least as far as new installs are concerned, so i'll approve this so we don't get any more installs set up this way. I do have a question on what happens if I have an EO already installed that was incorrectly setting limits, and we ship them this newer version of the operator. Will the newer EO automatically fix up the existing incorrect limits?

**Comment by jcantrill** [comment]
> QE has validated the fix for this in 4.2 at least as far as new installs are concerned, so i'll approve this so we don't get any more installs set up this way. I do have a question on what happens if I have an EO already installed that was incorrectly setting limits, and we ship them this newer version of the operator. Will the newer EO automatically fix up the existing incorrect limits?

@ewolinetz do you know offhand?  I would expect the CLO to recognize the difference in the CR and update the elasticsearch object causing the EO to see the difference and do a rolling restart of the cluster to reconcile.

**Comment by ewolinetz** [comment]
>> QE has validated the fix for this in 4.2 at least as far as new installs are concerned, so i'll approve this so we don't get any more installs set up this way. I do have a question on what happens if I have an EO already installed that was incorrectly setting limits, and we ship them this newer version of the operator. Will the newer EO automatically fix up the existing incorrect limits?

>  I would expect the CLO to recognize the difference in the CR and update the elasticsearch object causing the EO to see the difference and do a rolling restart of the cluster to reconcile.

As long as the elasticsearch CR is defined where it does not have a limit set for it, then yes, I believe this updated EO should correct an already deployed Deployment

**Pull request merged**
