### PR TITLE
Bug 1824006: Backported fix for ES ENV

### PR DESCRIPTION
**Pull request by igor-karpukhin**
This PR resolves the following bug: https://bugzilla.redhat.com/show_bug.cgi?id=1824006

It is a port of this PR https://github.com/openshift/elasticsearch-operator/pull/316 to 4.4 release + fix for E2E test.

### CODE REVIEW

**Comment by sdodson** [comment]
Where'd the new commit come from? If it's a backport from where?

**Comment by igor-karpukhin** [comment]
@sdodson We have E2E test that fails from time to time. Trying to fix that. This new commit just adds more debug output.

**Comment by igor-karpukhin** [comment]
@sdodson may I please have `cherry-pick-approved` label back?

**Comment by sdodson** [comment]
Can you please reference where the additional changes came from? It's fine if we're pulling in additional changes from upstream but I'd expect multiple commits with sufficiently detailed commit messages rather than one squashed commit which seems to lose some detail from the original commits.

@bparees can I get your thoughts on this backport?

**Comment by bparees** [comment]
@sdodson i agree that it would be good to get some context on why there seem to be additional/unrelated changes here. 

@igor-karpukhin I know it wasn't a clean cherry pick but the PR description and commit text at a minimum need to do a better job of explaining the changes (and if we don't need the test script changes, they should be left out).

**Comment by igor-karpukhin** [comment]
@sdodson @bparees There is only one change related to the EO logic, which is a backport from https://github.com/openshift/elasticsearch-operator/pull/316. Other changes are fixing the E2E test, which is fixed in 4.5+ but not fixed for 4.4. I have updated the PR description. Unfortunately, clean cherry-pick is not possible, because the 4.4 is missing some of the ENV comparison logic.

**Comment by sdodson** [comment]
Those two items could've been separate commits, anyway given the urgency of the bug being fixed approving this.

**Pull request merged**
