### PR TITLE
Bug 1842445: Drop curl verbosity in index management scripts

### PR DESCRIPTION
**Pull request by periklis**
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1842445

Needs backport: release-4.5

### CODE REVIEW

**Comment by periklis** [comment]
@syedriko The output of the BZ is not up2date. There used to be xtrace enabled for these scripts and this is solved by #371. 

/hold cancel

**Comment by syedriko** [comment]
> @syedriko The output of the BZ is not up2date. There used to be xtrace enabled for these scripts and this is solved by #371.
> 
> /hold cancel

Can we have the BZs up to date then? There seem to be two BZs, 1843080 and 1842445, both tracking the same thing and progressing independently. Should we leave 1843080 alone, fix 1842445 and then propagate the fix?

**Pull request merged**
