### PR TITLE
Bug 1812912: Bind ES node to POD_IP

### PR DESCRIPTION
**Pull request by jcantrill**
Fix:
* https://bugzilla.redhat.com/show_bug.cgi?id=1812912
* https://bugzilla.redhat.com/show_bug.cgi?id=1814851

 by binding to pod IP

4.4 backport of https://github.com/openshift/elasticsearch-operator/pull/270

### CODE REVIEW

**Comment by ewolinetz** [comment]
@jcantrill is the dep bump required?

**Comment by jcantrill** [comment]
> @jcantrill is the dep bump required?

The compile and tests failed without these changes which frankly I was surprised about

**Comment by ewolinetz** [comment]
> The compile and tests failed without these changes which frankly I was surprised about

Thats a little concerning

**Comment by ewolinetz** [comment]
/hold
i'm going to test this locally

**Comment by jcantrill** [comment]
cc @bparees

**Pull request merged**
