### PR TITLE
fixing up deploying latest version available to catalog

### PR DESCRIPTION
**Pull request by ewolinetz**
### Description
Fixing the upgrade script to ensure that we are trying to deploy a prior version of the EO from operatorhub that is in the catalog

/cc @blockloop @periklis

### CODE REVIEW

**Review by blockloop — APPROVED** [review]
/lgtm

**Comment by ewolinetz** [comment]
/test e2e-operator
ocp cluster failed to start up

**Review by blockloop — APPROVED** [review]
/lgtm

**Pull request merged**
