### PR TITLE
Bug 1841832: Removing calls to enforce and relax networkpolicy

### PR DESCRIPTION
**Pull request by ewolinetz**
Addresses inconsistencies seen with networkpolicy like in https://bugzilla.redhat.com/show_bug.cgi?id=1841832

### CODE REVIEW

**Comment by jcantrill** [comment]
@ewolinetz i see https://github.com/openshift/elasticsearch-operator/pull/375 has not merged. Does this mean there is no backport necessary and we can maybe close https://bugzilla.redhat.com/show_bug.cgi?id=1843715

**Comment by ewolinetz** [comment]
this is being manually cherrypicked into https://github.com/openshift/elasticsearch-operator/pull/386

**Pull request merged**
