### PR TITLE
Bug 1833142: Renamed kibana CR instance

### PR DESCRIPTION
**Pull request by igor-karpukhin**
Renamed kibana CR instance that EO is watching for from **instance** to **kibana**

### CODE REVIEW

**Comment by ewolinetz** [comment]
there will be additional tech debt to clean up the operator to create services/etc based on the CR name... but for now /lgtm

**Comment by igor-karpukhin** [comment]
> there will be additional tech debt to clean up the operator to create services/etc based on the CR name... but for now /lgtm

@ewolinetz  Sounds like a ticket for 4.6

**Pull request merged**
