### PR TITLE
LOG-1552: Suspend cronjobs when ES is scaled to zero nodes

### PR DESCRIPTION
**Pull request by periklis**
### Description
This is a manual backport of #723 to introduce suspending indexmanagement cronjobs when no elasticsearch nodes available. 

/cc @ewolinetz 
/assign @ewolinetz 

### Links
- JIRA: https://issues.redhat.com/browse/LOG-1552

### CODE REVIEW

**Comment by ewolinetz** [comment]
@periklis why does it look like `indexmanagement/reconcile` is missing a lot of logic from https://github.com/openshift/elasticsearch-operator/pull/723 ?

**Comment by periklis** [comment]
> @periklis why does it look like `indexmanagement/reconcile` is missing a lot of logic from #723 ?

The pkg split refactoring we did in #735 introduced some duplication work, e.g. to check if nodes are ready. This needs to be addressed in master by making this re-usable for pkg `elasticsearch` and `indexmanagement`. This work is not required here as per `indexmanagent` having direct access to `es.AnyNodeReady()`.

**Pull request merged**
