### PR TITLE
[release-4.1] Bug 1711044: Remove nodes that arent in CR

### PR DESCRIPTION
**Pull request by ewolinetz**
Cherry pick of https://github.com/openshift/elasticsearch-operator/pull/144

If a node has been removed from `spec.nodes` we want to no longer manage it and delete it accordingly.

NOTE: currently, when removing a node that has been established already, the operator will flag that a previously used UUID is no longer available and will mark this as an invalid config. You will also need to remove it from status.nodes as well.

ref: https://bugzilla.redhat.com/show_bug.cgi?id=1707875
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1711044

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
why does the automated cherry-pick introduce such a huge number of code changes?  do we really require adding 400k lines of code and removing 200k lines of code for a change of this nature?

**Comment by derekwaynecarr** [comment]
the linked pr has not yet been verified in master, and given the size of the code change, prefer we hold until its verified in master.

**Comment by ewolinetz** [comment]
@derekwaynecarr the issue is that our 4.1 release is with sdk version 0.0.7.0 and our master branch is on 0.7.0. so most of those changes are due to `dep ensure` to get our ci tests to continue to work. I can try to verify again if this fix can go in without said dep restrictions.

**Comment by ewolinetz** [comment]
I think the vendor directory got screwed up when trying to resolve a cherrypick command. If I just make the functional changes, this works.

I was unable to fix this branch's deps with a `git checkout release-4.1 -- ... `, closing and replacing with a cleaner cherry pick

**Pull request closed without merging**
