### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by georgettica**
using https://github.com/crate-ci/typos I found this typo (using this file for my own PR XD

### Description

/cc 
/assign 

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA:
- Enhancement proposal:

### CODE REVIEW

**Comment by georgettica** [comment]
didn't fill all of it as it was a super tiny PR. feel free to shove me off and tell me to fill it up before

**Comment by georgettica** [comment]
I know the tests are failing and I know how to fix. just thought it would be a smaller PR.

will invest time in this later

**Comment by xperimental** [comment]
@georgettica Is this just a test PR generated using the tool you mention? Are you working on extending it (aside from the failing unit test)? I'm doubting that there is only one typo in the whole codebase, although this would be good news indeed.

**Pull request closed without merging**
