### PR TITLE
Removing RBAC files and code that creates roles, bindings, etc at runtime

### PR DESCRIPTION
**Pull request by Red-GV**
This PR removes all RBAC files which are not in use the operator, code that is creating or updating any RBAC code, and any unused manifest files.

/cc @ewolinetz 
/assign @ewolinetz 

### Links
- JIRA: https://issues.redhat.com/browse/LOG-878

### CODE REVIEW

**Comment by Red-GV** [comment]
Should this to release-5.0 instead of master and after https://github.com/openshift/elasticsearch-operator/pull/649? 

The RBAc stuff is more general but I did remove the 4.7 manifests as well.

**Comment by periklis** [comment]
> Should this to release-5.0 instead of master and after #649?
> 
> The RBAc stuff is more general but I did remove the 4.7 manifests as well.

IMHO, this can still target master and we can discuss if we want to backport to `release-5.0` later. #649 is more of the sort "unblocking cluster-logging-operator-e2e test" for all elasticsearch-operator PRs right now.

**Review by periklis — COMMENTED** [review]
Are we sure that all these methods are unused? Otherwise looks good to me.

**Comment by Red-GV** [comment]
Are far as I can tell, they seem to be. I didn't see any of the unit tests break and when I deployed it, I didn't see anything glaring.

**Comment by ewolinetz** [comment]
@Red-GV just to refresh my memory, we didn't need to actually add anything into the csv RBAC definition for this correct?

**Comment by Red-GV** [comment]
@ewolinetz Nope. As far as I can tell, all the rules were already written into the csv, so no update was required.

**Comment by ewolinetz** [comment]
/hold
going to do some manual investigation on this

**Comment by ewolinetz** [comment]
closing as this appears to prevent prometheus from scraping metrics for elasticsearch.
I believe the jira card needs to be marked as obsolete as it no longer pertains to how we are handling rbac for EO

**Pull request closed without merging**
