### PR TITLE
Bug 1916911: fix es crd status incompatible when upgrad…

### PR DESCRIPTION
**Pull request by huikang**
### Description
Fix crd incompability during upgrading from 4.5 to 4

/cc @ewolinetz 
/assign @ewolinetz 

### Links
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1916911

### CODE REVIEW

**Comment by ewolinetz** [comment]
@huikang so we just needed to make a couple fields nullable and not the whole `status` structure?

**Comment by huikang** [comment]
> @huikang so we just needed to make a couple fields nullable and not the whole `status` structure?

Do you mean something like 

```go
type Elasticsearch struct {
	// Specification of the desired behavior of the Elasticsearch cluster
	Spec   ElasticsearchSpec   `json:"spec,omitempty"`

        // nullable
	Status ElasticsearchStatus `json:"status,omitempty"`
}
```
This looks odd as a CRD type struct. The generated CRD is

```
           status:
             description: ElasticsearchStatus defines the observed state of Elasticsearch
+            nullable: true
             properties:
```
The nullable property is only applicable to the 'status' field. I am not sure if it will be inherited by any embedded fields.

**Comment by ewolinetz** [comment]
@huikang I'm wondering if just marking those two fields as nullable was enough to resolve this bug since you were able to reproduce it.

**Comment by huikang** [comment]
> @huikang I'm wondering if just marking those two fields as nullable was enough to resolve this bug since you were able to reproduce it.

I see what you meant now. I have tested the installation with the PR and it worked (please checkout the last sentence of the my comment https://bugzilla.redhat.com/show_bug.cgi?id=1916911#c12. I should have emphasize this in the beginning of the comment).

**Comment by huikang** [comment]
@ewolinetz, FYI

Upgrading to 4.7 master from 4.5 operator

```
deployment openshift-operators-redhat/elasticsearch-operator-registry has been created
deployment.apps/elasticsearch-operator-registry condition met
service/elasticsearch-operator-registry created
catalogsource.operators.coreos.com/elasticsearch-catalog created
make[1]: Leaving directory '/root/go/src/github.com/openshift/elasticsearch-operator'
make[1]: Entering directory '/root/go/src/github.com/openshift/elasticsearch-operator'
olm_deploy/scripts/operator-install.sh
using existing project openshift-operators-redhat for operator installation
namespace/openshift-operators-redhat not labeled
##################
oc version
Client Version: openshift-clients-4.6.0-202006250705.p0-164-gffd683609
Server Version: 4.5.13
Kubernetes Version: v1.18.3+47c0e71
##################
operatorgroup.operators.coreos.com/elasticsearch-operator created
subscription.operators.coreos.com/elasticsearch-operator created
waiting for deployment openshift-operators-redhat/elasticsearch-operator - remaining attempts: 19
waiting for deployment openshift-operators-redhat/elasticsearch-operator - remaining attempts: 18
waiting for deployment openshift-operators-redhat/elasticsearch-operator - remaining attempts: 17
waiting for deployment openshift-operators-redhat/elasticsearch-operator - remaining attempts: 16
waiting for deployment openshift-operators-redhat/elasticsearch-operator - remaining attempts: 15
waiting for deployment openshift-operators-redhat/elasticsearch-operator - remaining attempts: 14
waiting for deployment openshift-operators-redhat/elasticsearch-operator - remaining attempts: 13
waiting for deployment openshift-operators-redhat/elasticsearch-operator - remaining attempts: 12
waiting for deployment openshift-operators-redhat/elasticsearch-operator - remaining attempts: 11
waiting for deployment openshift-operators-redhat/elasticsearch-operator - remaining attempts: 10
^Cmake[1]: *** [Makefile:222: elasticsearch-operator-install] Interrupt
make: *** [Makefile:107: deploy] Interrupt
```

After applying the PR

```
service/elasticsearch-operator-registry created
catalogsource.operators.coreos.com/elasticsearch-catalog created
make[1]: Leaving directory '/root/go/src/github.com/openshift/elasticsearch-operator'
make[1]: Entering directory '/root/go/src/github.com/openshift/elasticsearch-operator'
olm_deploy/scripts/operator-install.sh
using existing project openshift-operators-redhat for operator installation
namespace/openshift-operators-redhat labeled
##################
oc version
Client Version: openshift-clients-4.6.0-202006250705.p0-164-gffd683609
Server Version: 4.5.13
Kubernetes Version: v1.18.3+47c0e71
##################
operatorgroup.operators.coreos.com/elasticsearch-operator created
subscription.operators.coreos.com/elasticsearch-operator created
waiting for deployment openshift-operators-redhat/elasticsearch-operator - remaining attempts: 19
deployment openshift-operators-redhat/elasticsearch-operator has been created
deployment.apps/elasticsearch-operator condition met
make[1]: Leaving directory '/root/go/src/github.com/openshift/elasticsearch-operator'

```

**Comment by ewolinetz** [comment]
reminder we already have a 4.6.z bz to track this on, so we'll want to manually cherrypick and use that bz (https://bugzilla.redhat.com/show_bug.cgi?id=1918441)

**Comment by ewolinetz** [comment]
on hold because @huikang is unsure if this is the true root cause

**Comment by jcantrill** [comment]
hoping recent changes to CLO and https://github.com/openshift/elasticsearch-operator/pull/655 will resolve failing test

**Comment by ewolinetz** [comment]
@huikang looks like this needs to be rebased

**Comment by ewolinetz** [comment]
closing to be carried forward in https://github.com/openshift/elasticsearch-operator/pull/686

**Pull request closed without merging**
